apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-file
          emptyDir: {}
      containers:
        - name: log-writer
          image: tatuno/log-writer
          resources:
            limits:
              cpu: "100m"
              memory: "250Mi"
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
        - name: log-reader
          image: tatuno/log-reader:v0.5
          resources:
            limits:
              cpu: "100m"
              memory: "250Mi"
          envFrom:
            - configMapRef:
                name: message-config
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3001