apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
  namespace: log-output
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi