kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["create", "get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create"]
- apiGroups: ["stable.tatuno"]
  resources: ["dummysites"]
  verbs: ["get", "watch", "list"]
