apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-pong
          persistentVolumeClaim:
            claimName: ping-pong-claim
      containers:
        - name: ping-pong
          image: tatuno/ping-pong:v0.3
          volumeMounts:
          - name: shared-pong
            mountPath: /usr/src/app/pongs