apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: tatuno/ping-pong:v0.6
          env:
            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password