apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: tatuno/ping-pong:v1.3
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
          env:
            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            httpGet:
               path: /healthz
               port: 3002