kind: Namespace
apiVersion: v1
metadata:
  name: log-output
  labels:
    name: log-output
---
kind: Namespace
apiVersion: v1
metadata:
  name: todo
  labels:
    name: todo
---
kind: Namespace
apiVersion: v1
metadata:
  name: nats
  labels:
    name: nats
---
kind: Namespace
apiVersion: v1
metadata:
  name: argo-rollout
  labels:
    name: argo-rollout
---
kind: Namespace
apiVersion: v1
metadata:
<<<<<<< HEAD
=======
  name: argo-rollout
  labels:
    name: argo-rollout
---
kind: Namespace
apiVersion: v1
metadata:
>>>>>>> 98f8620e3f3bda984b6c8696363632d5cb7f12a9
  name: prometheus
  labels:
    name: prometheus