apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: daily-image
          emptyDir: {}
      containers:
        - name: todo-back
          image: tatuno/todo-back:v0.1
          volumeMounts:
          - name: daily-image
            mountPath: /usr/src/app/resources
        - name: todo-front
          image: tatuno/todo-front:v0.2