apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todo
  namespace: todo
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: enabled
        spec:
          containers:
          - name: daily-todo
            image: DAILY_TODO_IMAGE
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure