apiVersion: v1
kind: Service
metadata:
  name: todo-back-svc
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001