apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: todo-cpu-usage
  namespace: todo
spec:
  metrics:
  - name: todo-cpu-usage
    initialDelay: 10m
    successCondition: result < 0.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1657-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(
            sum(rate(container_cpu_usage_seconds_total{namespace="todo"}[10m]))
          )