apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-material-ingress
  namespace: todo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: todo-front-svc
            port:
              number: 2345
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: todo-back-svc
            port:
              number: 3001