apiVersion: ENC[AES256_GCM,data:dH8=,iv:UEPSUALnsuMpKWXjvHJwRxhxdFpxfu7okKJ02b122S4=,tag:GmOpocrUjKOzB1LNP3CiHg==,type:str]
kind: ENC[AES256_GCM,data:4uPTu8cL,iv:qvnesSATOT2pwsWWo52t3kMlvaPEOZWr6lC1Sqg3a5Y=,tag:DH1s6vBfIXRq0P4Nwv9YOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k1Eu9hmQ3deRFml8l40/a1G5Yg==,iv:xeHtyQcVUNotA8YKp7o5/rem+HkVEdveQZwPhoAUGmY=,tag:qzlsJ0cnGOysBMGYli+W8Q==,type:str]
    namespace: ENC[AES256_GCM,data:9DeMJg==,iv:jgvxPlqDB/+XEinBNaMVNg99UjxTfQYr7+FA91yWre4=,tag:Z74Six4bS5ejNS1fXRa5sQ==,type:str]
data:
    DISCORD_TOKEN: ENC[AES256_GCM,data:uOxs68PmQHKjQGdqRYBorzTVxpS1yCt42y8ueH5OYFp6hw8eb5opmkl/Ot1Jwtmsq0/0NPUJvoiKndNp+dGwwL/wioKgMqN2MHoILvsGWn9uZBev8O7Z9yYtZtwWLNq9,iv:kYYrUGftWsanSx0/el0YkWDW3FbPwAd72cwz1ROjU8c=,tag:YQdI73F+OmtkLsgKQRQupw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j8gm6an7ghtjz9q004nx86e95x0e4u3j4lwn7g0hmcjvtcu3nf3sjyytps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNEFqSUNVTEJ0Vk45K1JC
            TDA5eWp4MmZJUWZNVjFxQWo0emZLZW5ENW40CnhxZE5ldXAwOHVkMmthZzZDVm1L
            U01VbnYzc1FlSlArcitRcDZoTlo4SkEKLS0tIGU3d3pLT2R0RkZnb3hQRXFFdU5t
            SVk1VUQxQzlGemxsL0V6V0JpQStBdXMKxjGxTpx2qNdU0o9Q0X8PXmEefer4P6+Q
            n9QyPBGdPZkTl5rKY+L9f5AXmKqw/oHJFsHz6B94KhobSyH368i5dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T09:03:59Z"
    mac: ENC[AES256_GCM,data:Qg41vYW14mB5tcpxQSVSW2/JE/bPPhG3deDzhzL35fgC5jK1ZMnOr4YYEf+P0msIYQ1FOpzO1S5bf1kliFM1Z6MmvoIfU2fRNSGfA8S/XXIeowtTLyRsm+hxR0+01O06riOVBXiBJ6yx2Xg8k+RuWkVAVDmRwlAh1JUODflDds4=,iv:ELIRfBJ+c3X0pzZ4o53vCqo9wjkgh8gWLPbh/J6E0kU=,tag:yYmddHWu9Thkn3C9JAGVOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
